[package]
name = "gpio-server"
version = "0.1.0"
authors = ["John Merchant", "Matthew Croall"]
edition = "2018"

[dependencies]
actix-rt = "1.0.0"
actix-web = "2.0.0"
sysfs_gpio = "0.5"
env_logger = "*"