name: Rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Cross
      run: cargo install cross
    - name: Build
      run: cross build --target=armv7-unknown-linux-musleabihf --release --verbose
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.0
      with:
        # Comma-delimited list of path globs for asset files to upload
        files: ./target/armv7-unknown-linux-musleabihf/release/gpio-http-server
