name: Rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use nightly
      run: rustup default nightly
    - name: Update
      run: cargo update
    - name: Install toolchain
      run: sudo apt-get install -y gcc-arm-linux-gnueabihf
    - name: Add target
      run: rustup target add armv7-unknown-linux-gnueabihf
    - name: Configure cargo 
      run: |
        cat >>~/.cargo/config <<EOF
        [target.armv7-unknown-linux-gnueabihf]
        linker = "arm-linux-gnueabihf-gcc"
        EOF
    - name: Build
      run: cargo build --target=armv7-unknown-linux-gnueabihf--release
    - name: Upload asset to release
      uses: actions-github/upload-to-release@v1.0.0
      with:
        file: ./target/armv7-unknown-linux-gnueabihf/release/gpio-http-server
