name: Rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use nightly
      run: rustup default nightly
    - name: Update
      run: cargo update
    - name: Add target
      run: rustup target add armv7-unknown-linux-musleabihf
    - name: Install Cross
      run: cargo install --force --git https://github.com/rust-embedded/cross cross
    - name: Build
      run: cross build --target=armv7-unknown-linux-musleabihf --release --verbose -C linker=arm-linux-musleabihf-gcc
    - name: Upload asset to release
      uses: actions-github/upload-to-release@v1.0.0
      with:
        # Input file
        file: ./target/armv7-unknown-linux-musleabihf/release/gpio-http-server
